/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  AppInputPresets: () => import('#controllers/app_input_presets_controller'),
  Apps: () => import('#controllers/apps_controller'),
  Comfy: () => import('#controllers/comfy_controller'),
  MediaAssets: () => import('#controllers/media_assets_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  TaskGroups: () => import('#controllers/task_groups_controller'),
  Tasks: () => import('#controllers/tasks_controller'),
  Workflows: () => import('#controllers/workflows_controller'),
}
