/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AppInputPresetSchema extends BaseModel {
  static $columns = ['appId', 'createdAt', 'id', 'name', 'type', 'updatedAt', 'value'] as const
  $columns = AppInputPresetSchema.$columns
  @column()
  declare appId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}

export class AppTaskSchema extends BaseModel {
  static $columns = ['appId', 'appSnapshot', 'completedAt', 'createdAt', 'error', 'id', 'inputs', 'nodeRuns', 'outputs', 'requiresManualAction', 'startedAt', 'status', 'taskGroupId', 'updatedAt', 'variables', 'waitingNodeId'] as const
  $columns = AppTaskSchema.$columns
  @column()
  declare appId: number
  @column()
  declare appSnapshot: any
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare error: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inputs: any
  @column()
  declare nodeRuns: any
  @column()
  declare outputs: any
  @column()
  declare requiresManualAction: boolean
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare taskGroupId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare variables: any
  @column()
  declare waitingNodeId: string | null
}

export class AppSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'graph', 'id', 'name', 'status', 'updatedAt', 'variables'] as const
  $columns = AppSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare graph: any
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare variables: any
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LibraryAssetSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'displayName', 'id', 'mediaAssetId', 'tags', 'updatedAt'] as const
  $columns = LibraryAssetSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare displayName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mediaAssetId: number
  @column()
  declare tags: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MediaAssetSchema extends BaseModel {
  static $columns = ['comfyFilename', 'comfyName', 'comfySubfolder', 'comfyType', 'comfyUrl', 'createdAt', 'extension', 'hash', 'id', 'isStarred', 'localPath', 'mimeType', 'originalName', 'proxyForId', 'size', 'updatedAt'] as const
  $columns = MediaAssetSchema.$columns
  @column()
  declare comfyFilename: string
  @column()
  declare comfyName: string
  @column()
  declare comfySubfolder: string
  @column()
  declare comfyType: string
  @column()
  declare comfyUrl: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare extension: string | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isStarred: boolean
  @column()
  declare localPath: string
  @column()
  declare mimeType: string | null
  @column()
  declare originalName: string
  @column()
  declare proxyForId: number | null
  @column()
  declare size: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TaskGroupSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'sortOrder', 'updatedAt'] as const
  $columns = TaskGroupSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkflowSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'parameters', 'rawJson', 'results', 'status', 'updatedAt'] as const
  $columns = WorkflowSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column()
  declare parameters: any
  @column()
  declare rawJson: any
  @column()
  declare results: any
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
